DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (
City_code INT AUTO_INCREMENT  PRIMARY KEY,
city_name VARCHAR(50) NOT NULL,
city_pincode INT(8) NOT NULL
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NOT NULL,
mob INT(10) NOT NULL
);

COMMIT;